# Generated by Django 2.0.13 on 2019-08-13 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190813_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='files',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
